### ISSUE TITLE
Pre-launch todo

### ISSUE THREAD

**Issue by remy** [leftlogic/ffconf2016#2]
#### Items 2016-07-04 @ 9pm
- [x] reduce line heights and remove lines (in favour of the pattern without lines) - result should be slightly tighter headings and paragraphs
- [x] front page nav, workshops link to #workshops - rather than /workshops
- [x] update phase to only show session titles and descriptions (currently showing times and breaks etc)
- [x] "agreeing to our code of conduct" should have a period `.` at the end
- [x] On the `/workshops` page, we need the following copy added after the heading: "All workshops are run on 9 November and include a conference pass for the 10 November for £450+VAT. You can request to change the conference pass day, which will be granted based on availability."
- [x] I want to do some regigging of the workshop page, the content doesn't feel very structured ATM, which has only come to light after designs have been implemented.
- [x] Sold Out ticket button (on workshops) should be grey background with white text (IIRC this was missing from the PSDs)
- [x] Hover bg on navigation, can we use 50% white instead of solid white
- [ ] Can you remove link on the logo

---
#### Items _not_ required for pre-ticket launch
- [ ] Ticket page integrated with Ticket Taylor (re: Julie's ticketing system)
